### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by BaQs** [BaQs/pyEzviz#32]
Hi,

I've installed HACS package `ha-ezviz` (v. 0.0.2.7, which uses `pyezviz` v. 0.1.6.1) in Home Assistant and noticed that attempting to connect to my Ezviz account with only one camera (C1C PIR) throws an exception.

It looks like that the library doesn't support this camera model or (any?) non-battery powered camera without sensibility adjustments. This option is not available in the official Ezviz app.

Home Assistant log:

```
2021-02-03 22:27:10 WARNING (MainThread) [homeassistant.config_entries] Config entry for ezviz_cloud not ready yet. Retrying in 80 seconds
2021-02-03 22:28:32 ERROR (MainThread) [custom_components.ezviz_cloud.coordinator] Unexpected error fetching ezviz_cloud data: 'support_sensibility_adjust'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
    cameras = self.EzvizClient.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 270, in load_cameras
    camera.load()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 34, in load
    if self._device['supportExt']['support_sensibility_adjust']:
KeyError: 'support_sensibility_adjust'
```

BTW, great work!

__Originally posted by @olekbruks in https://github.com/BaQs/pyEzviz/issues/31__

**Comment by RenierM26** [comment]
Hi BaQs,,

This should work in the latest release "0.1.6.3". I've removed the "supportExt" check from pyezviz and also mostly use pagelist for the infos. 

I still need to fix the PTZ service call in the HA integration to match the snake_case naming change.

**Comment by surfzoid** [comment]
Hi,
Tu explain in the readme ezviz doesn't provide doc API.
Thoose camera are branded by InkVision, when i'm conecting by ssh to one of my pro hikvion, ino displayed are ezviz, so you be really happy to discover the inkvision sdk with api doc : https://www.hikvision.com/en/support/download/sdk/device-network-sdk--for-linux-64-bit-/
also plenty of other sdk like the famous and damed webcomponent :
http://www.hikvision.msk.ru/index/download/0-14

**Comment by RenierM26** [comment]
#31 issue was resolved and closed.
