### ISSUE TITLE
Error with device status

### ISSUE THREAD

**Issue by maframan** [BaQs/pyEzviz#63]
Hi,

when execute command "pyezviz -u <email_adress> -p ********** devices status "I obtain below error:

Traceback (most recent call last):
  File "/usr/local/bin/pyezviz", line 6, in <module>
    from pyezviz.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/pyezviz/__init__.py", line 1, in <module>
    from pyezviz.client import EzvizClient, PyEzvizError
  File "/usr/local/lib/python2.7/dist-packages/pyezviz/client.py", line 8, in <module>
    from .camera import EzvizCamera
  File "/usr/local/lib/python2.7/dist-packages/pyezviz/camera.py", line 2, in <module>
    import pyezviz.DeviceSwitchType
  File "/usr/local/lib/python2.7/dist-packages/pyezviz/DeviceSwitchType.py", line 3, in <module>
    @unique
NameError: name 'unique' is not defined

Thanks for your support.

**Comment by RenierM26** [comment]
Hi @maframan,

Your python version is too old. The library requires v3.6 and newer.
